FROM --platform=linux/amd64 python:3.9

ENV PYTHONUNBUFFERED 1

# Install Docker CLI
RUN apt-get update && apt-get install -y \
    curl \
    gnupg \
    lsb-release \
    apt-transport-https \
    ca-certificates \
    && curl -fsSL https://get.docker.com | sh

# OPTIONAL: sanity check Docker installed correctly
RUN docker --version

# Install Poetry
RUN curl -sSL https://install.python-poetry.org | python3 - --version 1.8.3
ENV PATH $PATH:/root/.local/bin
RUN poetry config virtualenvs.create false
RUN poetry config virtualenvs.in-project false

# Install dependencies
COPY ./compute_worker/pyproject.toml ./compute_worker/poetry.lock ./
RUN poetry install

# Copy code
ADD compute_worker .

CMD celery -A compute_worker worker \
    -l info \
    -Q compute-worker \
    -n compute-worker@%n \
    --concurrency=1
